on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

  jobs:
    publish:
      name: publish latest
      runs-on: ubuntu-latest
      needs: [ build ]

      # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
      permissions:
        id-token: write
        packages: write
        contents: read

      steps:
        - uses: actions/setup-go@v4
          with:
            go-version: 1.19
        - uses: actions/checkout@v4
        - uses: actions/cache@v3
          with:
            path: |
              ~/.cache/go-build
              ~/go/pkg/mod
            key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
            restore-keys: |
              ${{ runner.os }}-golang-
        - uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - uses: imjasonh/setup-ko@v0.6
        - run: |
            gh version 
